# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KairoSightWidgetAnalyze.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetAnalyze(object):
    def setupUi(self, WidgetAnalyze):
        WidgetAnalyze.setObjectName("WidgetAnalyze")
        WidgetAnalyze.resize(350, 512)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetAnalyze.sizePolicy().hasHeightForWidth())
        WidgetAnalyze.setSizePolicy(sizePolicy)
        WidgetAnalyze.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WidgetAnalyze)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSource = QtWidgets.QLabel(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSource.sizePolicy().hasHeightForWidth())
        self.labelSource.setSizePolicy(sizePolicy)
        self.labelSource.setTextFormat(QtCore.Qt.PlainText)
        self.labelSource.setObjectName("labelSource")
        self.horizontalLayout_2.addWidget(self.labelSource)
        self.comboBoxSource = QtWidgets.QComboBox(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSource.sizePolicy().hasHeightForWidth())
        self.comboBoxSource.setSizePolicy(sizePolicy)
        self.comboBoxSource.setObjectName("comboBoxSource")
        self.horizontalLayout_2.addWidget(self.comboBoxSource)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelPreps = QtWidgets.QLabel(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPreps.sizePolicy().hasHeightForWidth())
        self.labelPreps.setSizePolicy(sizePolicy)
        self.labelPreps.setTextFormat(QtCore.Qt.PlainText)
        self.labelPreps.setObjectName("labelPreps")
        self.horizontalLayout_7.addWidget(self.labelPreps)
        self.comboBoxPreps = QtWidgets.QComboBox(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPreps.sizePolicy().hasHeightForWidth())
        self.comboBoxPreps.setSizePolicy(sizePolicy)
        self.comboBoxPreps.setObjectName("comboBoxPreps")
        self.horizontalLayout_7.addWidget(self.comboBoxPreps)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelROIs = QtWidgets.QLabel(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelROIs.sizePolicy().hasHeightForWidth())
        self.labelROIs.setSizePolicy(sizePolicy)
        self.labelROIs.setTextFormat(QtCore.Qt.PlainText)
        self.labelROIs.setObjectName("labelROIs")
        self.horizontalLayout_5.addWidget(self.labelROIs)
        self.comboBoxROIs = QtWidgets.QComboBox(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxROIs.sizePolicy().hasHeightForWidth())
        self.comboBoxROIs.setSizePolicy(sizePolicy)
        self.comboBoxROIs.setCurrentText("")
        self.comboBoxROIs.setObjectName("comboBoxROIs")
        self.horizontalLayout_5.addWidget(self.comboBoxROIs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelAnalysis = QtWidgets.QLabel(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAnalysis.sizePolicy().hasHeightForWidth())
        self.labelAnalysis.setSizePolicy(sizePolicy)
        self.labelAnalysis.setTextFormat(QtCore.Qt.PlainText)
        self.labelAnalysis.setObjectName("labelAnalysis")
        self.horizontalLayout_6.addWidget(self.labelAnalysis)
        self.comboBoxAnalysis = QtWidgets.QComboBox(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAnalysis.sizePolicy().hasHeightForWidth())
        self.comboBoxAnalysis.setSizePolicy(sizePolicy)
        self.comboBoxAnalysis.setObjectName("comboBoxAnalysis")
        self.comboBoxAnalysis.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBoxAnalysis)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.tabWidgetAnalysisSteps = QtWidgets.QTabWidget(WidgetAnalyze)
        self.tabWidgetAnalysisSteps.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetAnalysisSteps.sizePolicy().hasHeightForWidth())
        self.tabWidgetAnalysisSteps.setSizePolicy(sizePolicy)
        self.tabWidgetAnalysisSteps.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tabWidgetAnalysisSteps.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidgetAnalysisSteps.setDocumentMode(False)
        self.tabWidgetAnalysisSteps.setTabBarAutoHide(False)
        self.tabWidgetAnalysisSteps.setObjectName("tabWidgetAnalysisSteps")
        self.tabCondition = QtWidgets.QWidget()
        self.tabCondition.setObjectName("tabCondition")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabCondition)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutCondition = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCondition.setObjectName("horizontalLayoutCondition")
        self.formLayoutCondition1 = QtWidgets.QFormLayout()
        self.formLayoutCondition1.setObjectName("formLayoutCondition1")
        self.signalTypeLabel = QtWidgets.QLabel(self.tabCondition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalTypeLabel.sizePolicy().hasHeightForWidth())
        self.signalTypeLabel.setSizePolicy(sizePolicy)
        self.signalTypeLabel.setObjectName("signalTypeLabel")
        self.formLayoutCondition1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.signalTypeLabel)
        self.signalTypeComboBox = QtWidgets.QComboBox(self.tabCondition)
        self.signalTypeComboBox.setObjectName("signalTypeComboBox")
        self.signalTypeComboBox.addItem("")
        self.signalTypeComboBox.addItem("")
        self.formLayoutCondition1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.signalTypeComboBox)
        self.roiCalculationLabel = QtWidgets.QLabel(self.tabCondition)
        self.roiCalculationLabel.setObjectName("roiCalculationLabel")
        self.formLayoutCondition1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.roiCalculationLabel)
        self.roiCalculationComboBox = QtWidgets.QComboBox(self.tabCondition)
        self.roiCalculationComboBox.setObjectName("roiCalculationComboBox")
        self.roiCalculationComboBox.addItem("")
        self.formLayoutCondition1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roiCalculationComboBox)
        self.horizontalLayoutCondition.addLayout(self.formLayoutCondition1)
        self.formLayoutCondition2 = QtWidgets.QFormLayout()
        self.formLayoutCondition2.setObjectName("formLayoutCondition2")
        self.filterFreqLabel = QtWidgets.QLabel(self.tabCondition)
        self.filterFreqLabel.setWordWrap(True)
        self.filterFreqLabel.setObjectName("filterFreqLabel")
        self.formLayoutCondition2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.filterFreqLabel)
        self.filterFreqSpinBox = QtWidgets.QSpinBox(self.tabCondition)
        self.filterFreqSpinBox.setMinimum(1)
        self.filterFreqSpinBox.setMaximum(200)
        self.filterFreqSpinBox.setProperty("value", 50)
        self.filterFreqSpinBox.setObjectName("filterFreqSpinBox")
        self.formLayoutCondition2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.filterFreqSpinBox)
        self.filterLabel = QtWidgets.QLabel(self.tabCondition)
        self.filterLabel.setObjectName("filterLabel")
        self.formLayoutCondition2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.filterLabel)
        self.filterCheckBox = QtWidgets.QCheckBox(self.tabCondition)
        self.filterCheckBox.setChecked(True)
        self.filterCheckBox.setObjectName("filterCheckBox")
        self.formLayoutCondition2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filterCheckBox)
        self.horizontalLayoutCondition.addLayout(self.formLayoutCondition2)
        self.verticalLayout_3.addLayout(self.horizontalLayoutCondition)
        self.buttonBoxCondition = QtWidgets.QDialogButtonBox(self.tabCondition)
        self.buttonBoxCondition.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.buttonBoxCondition.setObjectName("buttonBoxCondition")
        self.verticalLayout_3.addWidget(self.buttonBoxCondition)
        self.tabWidgetAnalysisSteps.addTab(self.tabCondition, "")
        self.tabPeakDetect = QtWidgets.QWidget()
        self.tabPeakDetect.setObjectName("tabPeakDetect")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabPeakDetect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayoutPeakDetect = QtWidgets.QFormLayout()
        self.formLayoutPeakDetect.setObjectName("formLayoutPeakDetect")
        self.thresholdLabel = QtWidgets.QLabel(self.tabPeakDetect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdLabel.sizePolicy().hasHeightForWidth())
        self.thresholdLabel.setSizePolicy(sizePolicy)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.formLayoutPeakDetect.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.thresholdLabel)
        self.thresholdDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.tabPeakDetect)
        self.thresholdDoubleSpinBox.setMinimum(0.01)
        self.thresholdDoubleSpinBox.setMaximum(0.99)
        self.thresholdDoubleSpinBox.setSingleStep(0.01)
        self.thresholdDoubleSpinBox.setProperty("value", 0.72)
        self.thresholdDoubleSpinBox.setObjectName("thresholdDoubleSpinBox")
        self.formLayoutPeakDetect.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.thresholdDoubleSpinBox)
        self.lockoutTimeLabel = QtWidgets.QLabel(self.tabPeakDetect)
        self.lockoutTimeLabel.setObjectName("lockoutTimeLabel")
        self.formLayoutPeakDetect.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lockoutTimeLabel)
        self.lockoutTimeSpinBox = QtWidgets.QSpinBox(self.tabPeakDetect)
        self.lockoutTimeSpinBox.setMinimum(1)
        self.lockoutTimeSpinBox.setMaximum(3000)
        self.lockoutTimeSpinBox.setProperty("value", 172)
        self.lockoutTimeSpinBox.setObjectName("lockoutTimeSpinBox")
        self.formLayoutPeakDetect.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lockoutTimeSpinBox)
        self.verticalLayout.addLayout(self.formLayoutPeakDetect)
        self.buttonBoxPeakDetect = QtWidgets.QDialogButtonBox(self.tabPeakDetect)
        self.buttonBoxPeakDetect.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.buttonBoxPeakDetect.setObjectName("buttonBoxPeakDetect")
        self.verticalLayout.addWidget(self.buttonBoxPeakDetect)
        self.tabWidgetAnalysisSteps.addTab(self.tabPeakDetect, "")
        self.tabProcess = QtWidgets.QWidget()
        self.tabProcess.setObjectName("tabProcess")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabProcess)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.processTableView = QtWidgets.QTableView(self.tabProcess)
        self.processTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.processTableView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.processTableView.setObjectName("processTableView")
        self.verticalLayout_4.addWidget(self.processTableView)
        self.buttonBoxProcess = QtWidgets.QDialogButtonBox(self.tabProcess)
        self.buttonBoxProcess.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.buttonBoxProcess.setObjectName("buttonBoxProcess")
        self.verticalLayout_4.addWidget(self.buttonBoxProcess)
        self.tabWidgetAnalysisSteps.addTab(self.tabProcess, "")
        self.verticalLayout_2.addWidget(self.tabWidgetAnalysisSteps)
        self.widgetPreview = GraphicsLayoutWidget(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPreview.sizePolicy().hasHeightForWidth())
        self.widgetPreview.setSizePolicy(sizePolicy)
        self.widgetPreview.setMinimumSize(QtCore.QSize(70, 200))
        self.widgetPreview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetPreview.setObjectName("widgetPreview")
        self.verticalLayout_2.addWidget(self.widgetPreview)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBoxAnalyze = QtWidgets.QDialogButtonBox(WidgetAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBoxAnalyze.sizePolicy().hasHeightForWidth())
        self.buttonBoxAnalyze.setSizePolicy(sizePolicy)
        self.buttonBoxAnalyze.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxAnalyze.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBoxAnalyze.setCenterButtons(False)
        self.buttonBoxAnalyze.setObjectName("buttonBoxAnalyze")
        self.horizontalLayout.addWidget(self.buttonBoxAnalyze)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(WidgetAnalyze)
        self.comboBoxROIs.setCurrentIndex(-1)
        self.tabWidgetAnalysisSteps.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(WidgetAnalyze)

    def retranslateUi(self, WidgetAnalyze):
        _translate = QtCore.QCoreApplication.translate
        WidgetAnalyze.setWindowTitle(_translate("WidgetAnalyze", "Analyze"))
        self.labelSource.setText(_translate("WidgetAnalyze", "Source:"))
        self.labelPreps.setText(_translate("WidgetAnalyze", "Prep:"))
        self.labelROIs.setText(_translate("WidgetAnalyze", "ROI:"))
        self.labelAnalysis.setText(_translate("WidgetAnalyze", "Analysis:"))
        self.comboBoxAnalysis.setItemText(0, _translate("WidgetAnalyze", "*New*"))
        self.signalTypeLabel.setText(_translate("WidgetAnalyze", "Signal Type:"))
        self.signalTypeComboBox.setItemText(0, _translate("WidgetAnalyze", "Voltage (Vm)"))
        self.signalTypeComboBox.setItemText(1, _translate("WidgetAnalyze", "Calcium (Ca)"))
        self.roiCalculationLabel.setText(_translate("WidgetAnalyze", "ROI Calculation:"))
        self.roiCalculationComboBox.setItemText(0, _translate("WidgetAnalyze", "Mean"))
        self.filterFreqLabel.setText(_translate("WidgetAnalyze", "Cutoff (Hz)"))
        self.filterLabel.setText(_translate("WidgetAnalyze", "Low Pass Filter"))
        self.tabWidgetAnalysisSteps.setTabText(self.tabWidgetAnalysisSteps.indexOf(self.tabCondition), _translate("WidgetAnalyze", "Condition"))
        self.thresholdLabel.setText(_translate("WidgetAnalyze", "Threshold (0 - 1)"))
        self.lockoutTimeLabel.setText(_translate("WidgetAnalyze", "Lockout Time (frames)"))
        self.tabWidgetAnalysisSteps.setTabText(self.tabWidgetAnalysisSteps.indexOf(self.tabPeakDetect), _translate("WidgetAnalyze", "Peak Detect"))
        self.tabWidgetAnalysisSteps.setTabText(self.tabWidgetAnalysisSteps.indexOf(self.tabProcess), _translate("WidgetAnalyze", "Process"))

from pyqtgraph.widgets.GraphicsLayoutWidget import GraphicsLayoutWidget
