# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\KairoSight_WindowMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, WindowMain):
        WindowMain.setObjectName("WindowMain")
        WindowMain.resize(886, 610)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WindowMain.sizePolicy().hasHeightForWidth())
        WindowMain.setSizePolicy(sizePolicy)
        WindowMain.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayoutWindowMain = QtWidgets.QHBoxLayout(WindowMain)
        self.horizontalLayoutWindowMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutWindowMain.setObjectName("horizontalLayoutWindowMain")
        self.LayoutVideo = QtWidgets.QVBoxLayout()
        self.LayoutVideo.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LayoutVideo.setObjectName("LayoutVideo")
        self.horizontalLayout_View = QtWidgets.QHBoxLayout()
        self.horizontalLayout_View.setSpacing(0)
        self.horizontalLayout_View.setObjectName("horizontalLayout_View")
        self.graphicsView = GraphicsWidget(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(256, 0))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_View.addWidget(self.graphicsView)
        self.LayoutVideo.addLayout(self.horizontalLayout_View)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalScrollBar = QtWidgets.QScrollBar(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setInvertedAppearance(False)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout.addWidget(self.horizontalScrollBar)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lcdNumber_frame = QtWidgets.QLCDNumber(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_frame.sizePolicy().hasHeightForWidth())
        self.lcdNumber_frame.setSizePolicy(sizePolicy)
        self.lcdNumber_frame.setMinimumSize(QtCore.QSize(40, 0))
        self.lcdNumber_frame.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lcdNumber_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_frame.setSmallDecimalPoint(False)
        self.lcdNumber_frame.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_frame.setObjectName("lcdNumber_frame")
        self.horizontalLayout.addWidget(self.lcdNumber_frame)
        self.lcdNumber_frame_n = QtWidgets.QLCDNumber(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_frame_n.sizePolicy().hasHeightForWidth())
        self.lcdNumber_frame_n.setSizePolicy(sizePolicy)
        self.lcdNumber_frame_n.setMinimumSize(QtCore.QSize(40, 0))
        self.lcdNumber_frame_n.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lcdNumber_frame_n.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_frame_n.setObjectName("lcdNumber_frame_n")
        self.horizontalLayout.addWidget(self.lcdNumber_frame_n)
        self.LayoutVideo.addLayout(self.horizontalLayout)
        self.horizontalLayoutWindowMain.addLayout(self.LayoutVideo)
        self.LayoutSteps = QtWidgets.QVBoxLayout()
        self.LayoutSteps.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.LayoutSteps.setObjectName("LayoutSteps")
        self.groupBoxPrep = QtWidgets.QGroupBox(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPrep.sizePolicy().hasHeightForWidth())
        self.groupBoxPrep.setSizePolicy(sizePolicy)
        self.groupBoxPrep.setMinimumSize(QtCore.QSize(600, 170))
        self.groupBoxPrep.setMaximumSize(QtCore.QSize(600, 170))
        self.groupBoxPrep.setObjectName("groupBoxPrep")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxPrep)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolBoxPrep_Props = QtWidgets.QToolBox(self.groupBoxPrep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxPrep_Props.sizePolicy().hasHeightForWidth())
        self.toolBoxPrep_Props.setSizePolicy(sizePolicy)
        self.toolBoxPrep_Props.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxPrep_Props.setObjectName("toolBoxPrep_Props")
        self.pageProps = QtWidgets.QWidget()
        self.pageProps.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageProps.sizePolicy().hasHeightForWidth())
        self.pageProps.setSizePolicy(sizePolicy)
        self.pageProps.setObjectName("pageProps")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageProps)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonNextPrep_Props = QtWidgets.QCommandLinkButton(self.pageProps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextPrep_Props.sizePolicy().hasHeightForWidth())
        self.buttonNextPrep_Props.setSizePolicy(sizePolicy)
        self.buttonNextPrep_Props.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextPrep_Props.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNextPrep_Props.setObjectName("buttonNextPrep_Props")
        self.horizontalLayout_2.addWidget(self.buttonNextPrep_Props)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.toolBoxPrep_Props.addItem(self.pageProps, "")
        self.pagePropsEdit = QtWidgets.QWidget()
        self.pagePropsEdit.setGeometry(QtCore.QRect(0, 0, 186, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pagePropsEdit.sizePolicy().hasHeightForWidth())
        self.pagePropsEdit.setSizePolicy(sizePolicy)
        self.pagePropsEdit.setObjectName("pagePropsEdit")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pagePropsEdit)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.frameRateLabel = QtWidgets.QLabel(self.pagePropsEdit)
        self.frameRateLabel.setObjectName("frameRateLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frameRateLabel)
        self.frameRateLineEdit = QtWidgets.QLineEdit(self.pagePropsEdit)
        self.frameRateLineEdit.setObjectName("frameRateLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frameRateLineEdit)
        self.scaleLabel = QtWidgets.QLabel(self.pagePropsEdit)
        self.scaleLabel.setObjectName("scaleLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.scaleLabel)
        self.scaleLineEdit = QtWidgets.QLineEdit(self.pagePropsEdit)
        self.scaleLineEdit.setObjectName("scaleLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scaleLineEdit)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.pagePropsEdit)
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.toolBoxPrep_Props.addItem(self.pagePropsEdit, "")
        self.horizontalLayout_3.addWidget(self.toolBoxPrep_Props)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.toolBoxPrep_Crop = QtWidgets.QToolBox(self.groupBoxPrep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxPrep_Crop.sizePolicy().hasHeightForWidth())
        self.toolBoxPrep_Crop.setSizePolicy(sizePolicy)
        self.toolBoxPrep_Crop.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxPrep_Crop.setObjectName("toolBoxPrep_Crop")
        self.pageCrop = QtWidgets.QWidget()
        self.pageCrop.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageCrop.sizePolicy().hasHeightForWidth())
        self.pageCrop.setSizePolicy(sizePolicy)
        self.pageCrop.setObjectName("pageCrop")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.pageCrop)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem4 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonNextPrep_Crop = QtWidgets.QCommandLinkButton(self.pageCrop)
        self.buttonNextPrep_Crop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextPrep_Crop.sizePolicy().hasHeightForWidth())
        self.buttonNextPrep_Crop.setSizePolicy(sizePolicy)
        self.buttonNextPrep_Crop.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextPrep_Crop.setMaximumSize(QtCore.QSize(80, 35))
        self.buttonNextPrep_Crop.setObjectName("buttonNextPrep_Crop")
        self.verticalLayout.addWidget(self.buttonNextPrep_Crop)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.checkBox_2 = QtWidgets.QCheckBox(self.pageCrop)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_16.addLayout(self.verticalLayout)
        self.toolBoxPrep_Crop.addItem(self.pageCrop, "")
        self.pageCropEdit = QtWidgets.QWidget()
        self.pageCropEdit.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageCropEdit.sizePolicy().hasHeightForWidth())
        self.pageCropEdit.setSizePolicy(sizePolicy)
        self.pageCropEdit.setObjectName("pageCropEdit")
        self.toolBoxPrep_Crop.addItem(self.pageCropEdit, "")
        self.horizontalLayout_3.addWidget(self.toolBoxPrep_Crop)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.toolBoxPrep_Mask = QtWidgets.QToolBox(self.groupBoxPrep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxPrep_Mask.sizePolicy().hasHeightForWidth())
        self.toolBoxPrep_Mask.setSizePolicy(sizePolicy)
        self.toolBoxPrep_Mask.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxPrep_Mask.setObjectName("toolBoxPrep_Mask")
        self.pageMask = QtWidgets.QWidget()
        self.pageMask.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageMask.sizePolicy().hasHeightForWidth())
        self.pageMask.setSizePolicy(sizePolicy)
        self.pageMask.setObjectName("pageMask")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.pageMask)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem8 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.buttonNextPrep_Mask = QtWidgets.QCommandLinkButton(self.pageMask)
        self.buttonNextPrep_Mask.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextPrep_Mask.sizePolicy().hasHeightForWidth())
        self.buttonNextPrep_Mask.setSizePolicy(sizePolicy)
        self.buttonNextPrep_Mask.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextPrep_Mask.setMaximumSize(QtCore.QSize(80, 35))
        self.buttonNextPrep_Mask.setObjectName("buttonNextPrep_Mask")
        self.verticalLayout_10.addWidget(self.buttonNextPrep_Mask)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.checkBox_3 = QtWidgets.QCheckBox(self.pageMask)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_7.addWidget(self.checkBox_3)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17.addLayout(self.verticalLayout_10)
        self.toolBoxPrep_Mask.addItem(self.pageMask, "")
        self.pageMaskEdit = QtWidgets.QWidget()
        self.pageMaskEdit.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageMaskEdit.sizePolicy().hasHeightForWidth())
        self.pageMaskEdit.setSizePolicy(sizePolicy)
        self.pageMaskEdit.setObjectName("pageMaskEdit")
        self.toolBoxPrep_Mask.addItem(self.pageMaskEdit, "")
        self.horizontalLayout_3.addWidget(self.toolBoxPrep_Mask)
        self.LayoutSteps.addWidget(self.groupBoxPrep)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.LayoutSteps.addItem(spacerItem11)
        self.groupBoxProc = QtWidgets.QGroupBox(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxProc.sizePolicy().hasHeightForWidth())
        self.groupBoxProc.setSizePolicy(sizePolicy)
        self.groupBoxProc.setMinimumSize(QtCore.QSize(600, 170))
        self.groupBoxProc.setMaximumSize(QtCore.QSize(600, 170))
        self.groupBoxProc.setObjectName("groupBoxProc")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBoxProc)
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.toolBoxProc_Normalize = QtWidgets.QToolBox(self.groupBoxProc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxProc_Normalize.sizePolicy().hasHeightForWidth())
        self.toolBoxProc_Normalize.setSizePolicy(sizePolicy)
        self.toolBoxProc_Normalize.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxProc_Normalize.setObjectName("toolBoxProc_Normalize")
        self.pageNormalize = QtWidgets.QWidget()
        self.pageNormalize.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageNormalize.sizePolicy().hasHeightForWidth())
        self.pageNormalize.setSizePolicy(sizePolicy)
        self.pageNormalize.setObjectName("pageNormalize")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageNormalize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem12 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem12)
        self.buttonNextProc_Norm = QtWidgets.QCommandLinkButton(self.pageNormalize)
        self.buttonNextProc_Norm.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextProc_Norm.sizePolicy().hasHeightForWidth())
        self.buttonNextProc_Norm.setSizePolicy(sizePolicy)
        self.buttonNextProc_Norm.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextProc_Norm.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNextProc_Norm.setObjectName("buttonNextProc_Norm")
        self.horizontalLayout_13.addWidget(self.buttonNextProc_Norm)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.toolBoxProc_Normalize.addItem(self.pageNormalize, "")
        self.pageNormalizeEdit = QtWidgets.QWidget()
        self.pageNormalizeEdit.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageNormalizeEdit.sizePolicy().hasHeightForWidth())
        self.pageNormalizeEdit.setSizePolicy(sizePolicy)
        self.pageNormalizeEdit.setObjectName("pageNormalizeEdit")
        self.toolBoxProc_Normalize.addItem(self.pageNormalizeEdit, "")
        self.horizontalLayout_14.addWidget(self.toolBoxProc_Normalize)
        spacerItem13 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.toolBoxProc_Filter = QtWidgets.QToolBox(self.groupBoxProc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxProc_Filter.sizePolicy().hasHeightForWidth())
        self.toolBoxProc_Filter.setSizePolicy(sizePolicy)
        self.toolBoxProc_Filter.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxProc_Filter.setObjectName("toolBoxProc_Filter")
        self.pageFilter = QtWidgets.QWidget()
        self.pageFilter.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageFilter.sizePolicy().hasHeightForWidth())
        self.pageFilter.setSizePolicy(sizePolicy)
        self.pageFilter.setObjectName("pageFilter")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.pageFilter)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem14 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.buttonNextProc_Filter = QtWidgets.QCommandLinkButton(self.pageFilter)
        self.buttonNextProc_Filter.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextProc_Filter.sizePolicy().hasHeightForWidth())
        self.buttonNextProc_Filter.setSizePolicy(sizePolicy)
        self.buttonNextProc_Filter.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextProc_Filter.setMaximumSize(QtCore.QSize(80, 35))
        self.buttonNextProc_Filter.setObjectName("buttonNextProc_Filter")
        self.verticalLayout_8.addWidget(self.buttonNextProc_Filter)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem15 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.checkBox_7 = QtWidgets.QCheckBox(self.pageFilter)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_12.addWidget(self.checkBox_7)
        spacerItem16 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.toolBoxProc_Filter.addItem(self.pageFilter, "")
        self.pageFilterEdit = QtWidgets.QWidget()
        self.pageFilterEdit.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageFilterEdit.sizePolicy().hasHeightForWidth())
        self.pageFilterEdit.setSizePolicy(sizePolicy)
        self.pageFilterEdit.setObjectName("pageFilterEdit")
        self.toolBoxProc_Filter.addItem(self.pageFilterEdit, "")
        self.horizontalLayout_14.addWidget(self.toolBoxProc_Filter)
        spacerItem17 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.toolBoxProc_SNR = QtWidgets.QToolBox(self.groupBoxProc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxProc_SNR.sizePolicy().hasHeightForWidth())
        self.toolBoxProc_SNR.setSizePolicy(sizePolicy)
        self.toolBoxProc_SNR.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxProc_SNR.setObjectName("toolBoxProc_SNR")
        self.pageSNR = QtWidgets.QWidget()
        self.pageSNR.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSNR.sizePolicy().hasHeightForWidth())
        self.pageSNR.setSizePolicy(sizePolicy)
        self.pageSNR.setObjectName("pageSNR")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.pageSNR)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem18 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem18)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.buttonNextProc_SNR = QtWidgets.QCommandLinkButton(self.pageSNR)
        self.buttonNextProc_SNR.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextProc_SNR.sizePolicy().hasHeightForWidth())
        self.buttonNextProc_SNR.setSizePolicy(sizePolicy)
        self.buttonNextProc_SNR.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextProc_SNR.setMaximumSize(QtCore.QSize(80, 35))
        self.buttonNextProc_SNR.setObjectName("buttonNextProc_SNR")
        self.verticalLayout_7.addWidget(self.buttonNextProc_SNR)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem19 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.checkBox_6 = QtWidgets.QCheckBox(self.pageSNR)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_11.addWidget(self.checkBox_6)
        spacerItem20 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem20)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18.addLayout(self.verticalLayout_7)
        self.toolBoxProc_SNR.addItem(self.pageSNR, "")
        self.pageSNREdit = QtWidgets.QWidget()
        self.pageSNREdit.setGeometry(QtCore.QRect(0, 0, 182, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSNREdit.sizePolicy().hasHeightForWidth())
        self.pageSNREdit.setSizePolicy(sizePolicy)
        self.pageSNREdit.setObjectName("pageSNREdit")
        self.toolBoxProc_SNR.addItem(self.pageSNREdit, "")
        self.horizontalLayout_14.addWidget(self.toolBoxProc_SNR)
        self.LayoutSteps.addWidget(self.groupBoxProc)
        spacerItem21 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.LayoutSteps.addItem(spacerItem21)
        self.groupBoxAnalysis = QtWidgets.QGroupBox(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxAnalysis.sizePolicy().hasHeightForWidth())
        self.groupBoxAnalysis.setSizePolicy(sizePolicy)
        self.groupBoxAnalysis.setMinimumSize(QtCore.QSize(600, 170))
        self.groupBoxAnalysis.setMaximumSize(QtCore.QSize(600, 170))
        self.groupBoxAnalysis.setCheckable(False)
        self.groupBoxAnalysis.setObjectName("groupBoxAnalysis")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBoxAnalysis)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolBoxAnalysis_Isolate = QtWidgets.QToolBox(self.groupBoxAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxAnalysis_Isolate.sizePolicy().hasHeightForWidth())
        self.toolBoxAnalysis_Isolate.setSizePolicy(sizePolicy)
        self.toolBoxAnalysis_Isolate.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxAnalysis_Isolate.setObjectName("toolBoxAnalysis_Isolate")
        self.pageIsolate = QtWidgets.QWidget()
        self.pageIsolate.setGeometry(QtCore.QRect(0, 0, 180, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageIsolate.sizePolicy().hasHeightForWidth())
        self.pageIsolate.setSizePolicy(sizePolicy)
        self.pageIsolate.setObjectName("pageIsolate")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.pageIsolate)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem22 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem22)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonNextAnalysis_Isolate = QtWidgets.QCommandLinkButton(self.pageIsolate)
        self.buttonNextAnalysis_Isolate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextAnalysis_Isolate.sizePolicy().hasHeightForWidth())
        self.buttonNextAnalysis_Isolate.setSizePolicy(sizePolicy)
        self.buttonNextAnalysis_Isolate.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextAnalysis_Isolate.setMaximumSize(QtCore.QSize(80, 35))
        self.buttonNextAnalysis_Isolate.setObjectName("buttonNextAnalysis_Isolate")
        self.verticalLayout_4.addWidget(self.buttonNextAnalysis_Isolate)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem23 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem23)
        self.checkBox_8 = QtWidgets.QCheckBox(self.pageIsolate)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_4.addWidget(self.checkBox_8)
        spacerItem24 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem24)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.toolBoxAnalysis_Isolate.addItem(self.pageIsolate, "")
        self.pageIsolateEdit = QtWidgets.QWidget()
        self.pageIsolateEdit.setGeometry(QtCore.QRect(0, 0, 180, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageIsolateEdit.sizePolicy().hasHeightForWidth())
        self.pageIsolateEdit.setSizePolicy(sizePolicy)
        self.pageIsolateEdit.setObjectName("pageIsolateEdit")
        self.toolBoxAnalysis_Isolate.addItem(self.pageIsolateEdit, "")
        self.horizontalLayout_5.addWidget(self.toolBoxAnalysis_Isolate)
        spacerItem25 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem25)
        self.toolBoxAnalysis_Analyze = QtWidgets.QToolBox(self.groupBoxAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxAnalysis_Analyze.sizePolicy().hasHeightForWidth())
        self.toolBoxAnalysis_Analyze.setSizePolicy(sizePolicy)
        self.toolBoxAnalysis_Analyze.setMinimumSize(QtCore.QSize(180, 120))
        self.toolBoxAnalysis_Analyze.setObjectName("toolBoxAnalysis_Analyze")
        self.pageAnalyze = QtWidgets.QWidget()
        self.pageAnalyze.setGeometry(QtCore.QRect(0, 0, 180, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageAnalyze.sizePolicy().hasHeightForWidth())
        self.pageAnalyze.setSizePolicy(sizePolicy)
        self.pageAnalyze.setObjectName("pageAnalyze")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.pageAnalyze)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem26 = QtWidgets.QSpacerItem(73, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.buttonNextAnalysis_Analyze = QtWidgets.QCommandLinkButton(self.pageAnalyze)
        self.buttonNextAnalysis_Analyze.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNextAnalysis_Analyze.sizePolicy().hasHeightForWidth())
        self.buttonNextAnalysis_Analyze.setSizePolicy(sizePolicy)
        self.buttonNextAnalysis_Analyze.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNextAnalysis_Analyze.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNextAnalysis_Analyze.setObjectName("buttonNextAnalysis_Analyze")
        self.horizontalLayout_8.addWidget(self.buttonNextAnalysis_Analyze)
        self.toolBoxAnalysis_Analyze.addItem(self.pageAnalyze, "")
        self.pageAnalyzeEdit = QtWidgets.QWidget()
        self.pageAnalyzeEdit.setGeometry(QtCore.QRect(0, 0, 180, 83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageAnalyzeEdit.sizePolicy().hasHeightForWidth())
        self.pageAnalyzeEdit.setSizePolicy(sizePolicy)
        self.pageAnalyzeEdit.setObjectName("pageAnalyzeEdit")
        self.toolBoxAnalysis_Analyze.addItem(self.pageAnalyzeEdit, "")
        self.horizontalLayout_5.addWidget(self.toolBoxAnalysis_Analyze)
        self.LayoutSteps.addWidget(self.groupBoxAnalysis)
        self.textBrowser_Feedback = QtWidgets.QTextBrowser(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Feedback.sizePolicy().hasHeightForWidth())
        self.textBrowser_Feedback.setSizePolicy(sizePolicy)
        self.textBrowser_Feedback.setMinimumSize(QtCore.QSize(0, 50))
        self.textBrowser_Feedback.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textBrowser_Feedback.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.textBrowser_Feedback.setObjectName("textBrowser_Feedback")
        self.LayoutSteps.addWidget(self.textBrowser_Feedback)
        self.horizontalLayoutWindowMain.addLayout(self.LayoutSteps)

        self.retranslateUi(WindowMain)
        self.toolBoxPrep_Props.setCurrentIndex(0)
        self.toolBoxPrep_Crop.setCurrentIndex(0)
        self.toolBoxPrep_Mask.setCurrentIndex(0)
        self.toolBoxProc_Normalize.setCurrentIndex(0)
        self.toolBoxProc_Filter.setCurrentIndex(0)
        self.toolBoxProc_SNR.setCurrentIndex(0)
        self.toolBoxAnalysis_Isolate.setCurrentIndex(0)
        self.toolBoxAnalysis_Analyze.setCurrentIndex(0)
        self.horizontalScrollBar.valueChanged['int'].connect(self.lcdNumber_frame.display)
        QtCore.QMetaObject.connectSlotsByName(WindowMain)

    def retranslateUi(self, WindowMain):
        _translate = QtCore.QCoreApplication.translate
        WindowMain.setWindowTitle(_translate("WindowMain", "KairoSight - Main Window"))
        self.groupBoxPrep.setTitle(_translate("WindowMain", "Preparation"))
        self.buttonNextPrep_Props.setAccessibleName(_translate("WindowMain", "Properties"))
        self.buttonNextPrep_Props.setText(_translate("WindowMain", "Next"))
        self.toolBoxPrep_Props.setItemText(self.toolBoxPrep_Props.indexOf(self.pageProps), _translate("WindowMain", "Properties"))
        self.frameRateLabel.setText(_translate("WindowMain", "Frame Rate (fps)"))
        self.scaleLabel.setText(_translate("WindowMain", "Scale (cm/px)"))
        self.pushButton_2.setText(_translate("WindowMain", "Reset"))
        self.toolBoxPrep_Props.setItemText(self.toolBoxPrep_Props.indexOf(self.pagePropsEdit), _translate("WindowMain", "<Edit>"))
        self.buttonNextPrep_Crop.setAccessibleName(_translate("WindowMain", "Crop"))
        self.buttonNextPrep_Crop.setText(_translate("WindowMain", "Next"))
        self.checkBox_2.setText(_translate("WindowMain", "Skip"))
        self.toolBoxPrep_Crop.setItemText(self.toolBoxPrep_Crop.indexOf(self.pageCrop), _translate("WindowMain", "Crop"))
        self.toolBoxPrep_Crop.setItemText(self.toolBoxPrep_Crop.indexOf(self.pageCropEdit), _translate("WindowMain", "<Edit>"))
        self.buttonNextPrep_Mask.setAccessibleName(_translate("WindowMain", "Mask"))
        self.buttonNextPrep_Mask.setText(_translate("WindowMain", "Next"))
        self.checkBox_3.setText(_translate("WindowMain", "Skip"))
        self.toolBoxPrep_Mask.setItemText(self.toolBoxPrep_Mask.indexOf(self.pageMask), _translate("WindowMain", "Mask"))
        self.toolBoxPrep_Mask.setItemText(self.toolBoxPrep_Mask.indexOf(self.pageMaskEdit), _translate("WindowMain", "<Edit>"))
        self.groupBoxProc.setTitle(_translate("WindowMain", "Processing"))
        self.buttonNextProc_Norm.setAccessibleName(_translate("WindowMain", "Normalize"))
        self.buttonNextProc_Norm.setText(_translate("WindowMain", "Next"))
        self.toolBoxProc_Normalize.setItemText(self.toolBoxProc_Normalize.indexOf(self.pageNormalize), _translate("WindowMain", "Normalize"))
        self.toolBoxProc_Normalize.setItemText(self.toolBoxProc_Normalize.indexOf(self.pageNormalizeEdit), _translate("WindowMain", "<Edit>"))
        self.buttonNextProc_Filter.setAccessibleName(_translate("WindowMain", "Filter"))
        self.buttonNextProc_Filter.setText(_translate("WindowMain", "Next"))
        self.checkBox_7.setText(_translate("WindowMain", "Skip"))
        self.toolBoxProc_Filter.setItemText(self.toolBoxProc_Filter.indexOf(self.pageFilter), _translate("WindowMain", "Filter"))
        self.toolBoxProc_Filter.setItemText(self.toolBoxProc_Filter.indexOf(self.pageFilterEdit), _translate("WindowMain", "<Edit>"))
        self.buttonNextProc_SNR.setAccessibleName(_translate("WindowMain", "SNR"))
        self.buttonNextProc_SNR.setText(_translate("WindowMain", "Next"))
        self.checkBox_6.setText(_translate("WindowMain", "Skip"))
        self.toolBoxProc_SNR.setItemText(self.toolBoxProc_SNR.indexOf(self.pageSNR), _translate("WindowMain", "Signal-to-Noise Ratio (SNR)"))
        self.toolBoxProc_SNR.setItemText(self.toolBoxProc_SNR.indexOf(self.pageSNREdit), _translate("WindowMain", "<Edit>"))
        self.groupBoxAnalysis.setTitle(_translate("WindowMain", "Analysis"))
        self.buttonNextAnalysis_Isolate.setAccessibleName(_translate("WindowMain", "Isolate"))
        self.buttonNextAnalysis_Isolate.setText(_translate("WindowMain", "Next"))
        self.checkBox_8.setText(_translate("WindowMain", "Skip"))
        self.toolBoxAnalysis_Isolate.setItemText(self.toolBoxAnalysis_Isolate.indexOf(self.pageIsolate), _translate("WindowMain", "Isolate"))
        self.toolBoxAnalysis_Isolate.setItemText(self.toolBoxAnalysis_Isolate.indexOf(self.pageIsolateEdit), _translate("WindowMain", "<Edit>"))
        self.buttonNextAnalysis_Analyze.setAccessibleName(_translate("WindowMain", "Analyze"))
        self.buttonNextAnalysis_Analyze.setText(_translate("WindowMain", "Next"))
        self.toolBoxAnalysis_Analyze.setItemText(self.toolBoxAnalysis_Analyze.indexOf(self.pageAnalyze), _translate("WindowMain", "Analyze"))
        self.toolBoxAnalysis_Analyze.setItemText(self.toolBoxAnalysis_Analyze.indexOf(self.pageAnalyzeEdit), _translate("WindowMain", "<Edit>"))
from ui.graphicswidget import GraphicsWidget
