# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KairoSight_WindowMain_Retro.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1129, 632)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 111, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.load_image_tools_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.load_image_tools_vl.setContentsMargins(0, 0, 0, 0)
        self.load_image_tools_vl.setObjectName("load_image_tools_vl")
        self.file_list = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.file_list.setObjectName("file_list")
        self.load_image_tools_vl.addWidget(self.file_list)
        self.SelectDirectoryButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SelectDirectoryButton.setObjectName("SelectDirectoryButton")
        self.load_image_tools_vl.addWidget(self.SelectDirectoryButton)
        self.LoadButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.LoadButton.setObjectName("LoadButton")
        self.load_image_tools_vl.addWidget(self.LoadButton)
        self.RefreshButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RefreshButton.setObjectName("RefreshButton")
        self.load_image_tools_vl.addWidget(self.RefreshButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 410, 161, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.image_properties_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.image_properties_vl.setContentsMargins(0, 0, 0, 0)
        self.image_properties_vl.setObjectName("image_properties_vl")
        self.image_prep_header = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.image_prep_header.setFont(font)
        self.image_prep_header.setObjectName("image_prep_header")
        self.image_properties_vl.addWidget(self.image_prep_header)
        self.frame_rate_hl = QtWidgets.QHBoxLayout()
        self.frame_rate_hl.setObjectName("frame_rate_hl")
        self.frame_rate_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.frame_rate_label.setObjectName("frame_rate_label")
        self.frame_rate_hl.addWidget(self.frame_rate_label)
        self.frame_rate_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.frame_rate_edit.setEnabled(False)
        self.frame_rate_edit.setObjectName("frame_rate_edit")
        self.frame_rate_hl.addWidget(self.frame_rate_edit)
        self.image_properties_vl.addLayout(self.frame_rate_hl)
        self.image_scale_hl = QtWidgets.QHBoxLayout()
        self.image_scale_hl.setObjectName("image_scale_hl")
        self.image_scale_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.image_scale_label.setObjectName("image_scale_label")
        self.image_scale_hl.addWidget(self.image_scale_label)
        self.image_scale_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.image_scale_edit.setEnabled(False)
        self.image_scale_edit.setObjectName("image_scale_edit")
        self.image_scale_hl.addWidget(self.image_scale_edit)
        self.image_properties_vl.addLayout(self.image_scale_hl)
        self.dual_image_hl = QtWidgets.QHBoxLayout()
        self.dual_image_hl.setObjectName("dual_image_hl")
        self.dual_image_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.dual_image_checkbox.setEnabled(False)
        self.dual_image_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dual_image_checkbox.setObjectName("dual_image_checkbox")
        self.dual_image_hl.addWidget(self.dual_image_checkbox)
        spacerItem = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.dual_image_hl.addItem(spacerItem)
        self.image_properties_vl.addLayout(self.dual_image_hl)
        self.start_prep_hl = QtWidgets.QHBoxLayout()
        self.start_prep_hl.setObjectName("start_prep_hl")
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.start_prep_hl.addItem(spacerItem1)
        self.start_prep_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.start_prep_button.setEnabled(False)
        self.start_prep_button.setObjectName("start_prep_button")
        self.start_prep_hl.addWidget(self.start_prep_button)
        self.image_properties_vl.addLayout(self.start_prep_hl)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(130, 10, 551, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.mpl_vl_window = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.mpl_vl_window.setContentsMargins(0, 0, 0, 0)
        self.mpl_vl_window.setSpacing(0)
        self.mpl_vl_window.setObjectName("mpl_vl_window")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(690, 10, 421, 391))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.mpl_sigvl_window = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.mpl_sigvl_window.setContentsMargins(0, 0, 0, 0)
        self.mpl_sigvl_window.setObjectName("mpl_sigvl_window")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SelectDirectoryButton.setText(_translate("MainWindow", "Select Directory"))
        self.LoadButton.setText(_translate("MainWindow", "Load"))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.image_prep_header.setText(_translate("MainWindow", "Image Properties:"))
        self.frame_rate_label.setText(_translate("MainWindow", "Frame Rate (fps): "))
        self.image_scale_label.setText(_translate("MainWindow", "      Scale (px/cm): "))
        self.dual_image_checkbox.setText(_translate("MainWindow", "Dual Image:  "))
        self.start_prep_button.setText(_translate("MainWindow", "Start Preparation"))

