# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KairoSightWidgetSplit.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetSplit(object):
    def setupUi(self, WidgetSplit):
        WidgetSplit.setObjectName("WidgetSplit")
        WidgetSplit.resize(240, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetSplit.sizePolicy().hasHeightForWidth())
        WidgetSplit.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(WidgetSplit)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(WidgetSplit)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.lockDimensionsLabel = QtWidgets.QLabel(self.groupBox_3)
        self.lockDimensionsLabel.setObjectName("lockDimensionsLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lockDimensionsLabel)
        self.lockDimensionsCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.lockDimensionsCheckBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lockDimensionsCheckBox.setChecked(True)
        self.lockDimensionsCheckBox.setObjectName("lockDimensionsCheckBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lockDimensionsCheckBox)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(WidgetSplit)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.originXLabel = QtWidgets.QLabel(self.groupBox)
        self.originXLabel.setObjectName("originXLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.originXLabel)
        self.originXSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.originXSpinBox.setObjectName("originXSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originXSpinBox)
        self.originYLabel = QtWidgets.QLabel(self.groupBox)
        self.originYLabel.setObjectName("originYLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.originYLabel)
        self.originYSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.originYSpinBox.setObjectName("originYSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.originYSpinBox)
        self.widthLabel = QtWidgets.QLabel(self.groupBox)
        self.widthLabel.setObjectName("widthLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.widthLabel)
        self.widthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widthSpinBox)
        self.heightLabel = QtWidgets.QLabel(self.groupBox)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.heightSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.heightSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(WidgetSplit)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.originYLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.originYLabel_2.setObjectName("originYLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.originYLabel_2)
        self.originYSpinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.originYSpinBox_2.setObjectName("originYSpinBox_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.originYSpinBox_2)
        self.widthLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.widthLabel_2.setObjectName("widthLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.widthLabel_2)
        self.widthSpinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.widthSpinBox_2.setObjectName("widthSpinBox_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widthSpinBox_2)
        self.heightLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.heightLabel_2.setObjectName("heightLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.heightLabel_2)
        self.heightSpinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.heightSpinBox_2.setObjectName("heightSpinBox_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.heightSpinBox_2)
        self.originXLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.originXLabel_2.setObjectName("originXLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.originXLabel_2)
        self.originXSpinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.originXSpinBox_2.setObjectName("originXSpinBox_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originXSpinBox_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(WidgetSplit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(WidgetSplit)
        QtCore.QMetaObject.connectSlotsByName(WidgetSplit)

    def retranslateUi(self, WidgetSplit):
        _translate = QtCore.QCoreApplication.translate
        WidgetSplit.setWindowTitle(_translate("WidgetSplit", "Split Video"))
        self.groupBox_3.setTitle(_translate("WidgetSplit", "Options"))
        self.lockDimensionsLabel.setText(_translate("WidgetSplit", "Lock Dimensions"))
        self.groupBox.setTitle(_translate("WidgetSplit", "Signal A"))
        self.originXLabel.setText(_translate("WidgetSplit", "Origin X"))
        self.originYLabel.setText(_translate("WidgetSplit", "Origin Y"))
        self.widthLabel.setText(_translate("WidgetSplit", "Width"))
        self.heightLabel.setText(_translate("WidgetSplit", "Height"))
        self.groupBox_2.setTitle(_translate("WidgetSplit", "Signal B (NEW)"))
        self.originYLabel_2.setText(_translate("WidgetSplit", "Origin Y"))
        self.widthLabel_2.setText(_translate("WidgetSplit", "Width"))
        self.heightLabel_2.setText(_translate("WidgetSplit", "Height"))
        self.originXLabel_2.setText(_translate("WidgetSplit", "Origin X"))

