# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KairoSightWidgetIsolate.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetIsolate(object):
    def setupUi(self, WidgetIsolate):
        WidgetIsolate.setObjectName("WidgetIsolate")
        WidgetIsolate.resize(344, 343)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetIsolate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelSource = QtWidgets.QLabel(WidgetIsolate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSource.sizePolicy().hasHeightForWidth())
        self.labelSource.setSizePolicy(sizePolicy)
        self.labelSource.setTextFormat(QtCore.Qt.PlainText)
        self.labelSource.setObjectName("labelSource")
        self.horizontalLayout_2.addWidget(self.labelSource)
        self.comboBoxSource = QtWidgets.QComboBox(WidgetIsolate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSource.sizePolicy().hasHeightForWidth())
        self.comboBoxSource.setSizePolicy(sizePolicy)
        self.comboBoxSource.setObjectName("comboBoxSource")
        self.horizontalLayout_2.addWidget(self.comboBoxSource)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelROIs = QtWidgets.QLabel(WidgetIsolate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelROIs.sizePolicy().hasHeightForWidth())
        self.labelROIs.setSizePolicy(sizePolicy)
        self.labelROIs.setTextFormat(QtCore.Qt.PlainText)
        self.labelROIs.setObjectName("labelROIs")
        self.horizontalLayout_5.addWidget(self.labelROIs)
        self.comboBoxROIs = QtWidgets.QComboBox(WidgetIsolate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxROIs.sizePolicy().hasHeightForWidth())
        self.comboBoxROIs.setSizePolicy(sizePolicy)
        self.comboBoxROIs.setObjectName("comboBoxROIs")
        self.comboBoxROIs.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxROIs)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabWidgetRoiTypes = QtWidgets.QTabWidget(WidgetIsolate)
        self.tabWidgetRoiTypes.setEnabled(True)
        self.tabWidgetRoiTypes.setTabBarAutoHide(False)
        self.tabWidgetRoiTypes.setObjectName("tabWidgetRoiTypes")
        self.tabCircle = QtWidgets.QWidget()
        self.tabCircle.setObjectName("tabCircle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabCircle)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayoutCenter = QtWidgets.QFormLayout()
        self.formLayoutCenter.setObjectName("formLayoutCenter")
        self.originXLabel = QtWidgets.QLabel(self.tabCircle)
        self.originXLabel.setObjectName("originXLabel")
        self.formLayoutCenter.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.originXLabel)
        self.originXLineEdit = QtWidgets.QLineEdit(self.tabCircle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originXLineEdit.sizePolicy().hasHeightForWidth())
        self.originXLineEdit.setSizePolicy(sizePolicy)
        self.originXLineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.originXLineEdit.setObjectName("originXLineEdit")
        self.formLayoutCenter.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originXLineEdit)
        self.originYLabel = QtWidgets.QLabel(self.tabCircle)
        self.originYLabel.setObjectName("originYLabel")
        self.formLayoutCenter.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.originYLabel)
        self.originYLineEdit = QtWidgets.QLineEdit(self.tabCircle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originYLineEdit.sizePolicy().hasHeightForWidth())
        self.originYLineEdit.setSizePolicy(sizePolicy)
        self.originYLineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.originYLineEdit.setObjectName("originYLineEdit")
        self.formLayoutCenter.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.originYLineEdit)
        self.horizontalLayout_3.addLayout(self.formLayoutCenter)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayoutRadius = QtWidgets.QFormLayout()
        self.formLayoutRadius.setObjectName("formLayoutRadius")
        self.radiusLabel = QtWidgets.QLabel(self.tabCircle)
        self.radiusLabel.setObjectName("radiusLabel")
        self.formLayoutRadius.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radiusLabel)
        self.radiusLineEdit = QtWidgets.QSpinBox(self.tabCircle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusLineEdit.sizePolicy().hasHeightForWidth())
        self.radiusLineEdit.setSizePolicy(sizePolicy)
        self.radiusLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.radiusLineEdit.setObjectName("radiusLineEdit")
        self.formLayoutRadius.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radiusLineEdit)
        self.horizontalLayout_3.addLayout(self.formLayoutRadius)
        self.tabWidgetRoiTypes.addTab(self.tabCircle, "")
        self.tabPoly = QtWidgets.QWidget()
        self.tabPoly.setObjectName("tabPoly")
        self.tabWidgetRoiTypes.addTab(self.tabPoly, "")
        self.verticalLayout.addWidget(self.tabWidgetRoiTypes)
        self.groupBoxTime = QtWidgets.QGroupBox(WidgetIsolate)
        self.groupBoxTime.setObjectName("groupBoxTime")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxTime)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBoxTimeAll = QtWidgets.QCheckBox(self.groupBoxTime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxTimeAll.sizePolicy().hasHeightForWidth())
        self.checkBoxTimeAll.setSizePolicy(sizePolicy)
        self.checkBoxTimeAll.setChecked(True)
        self.checkBoxTimeAll.setObjectName("checkBoxTimeAll")
        self.horizontalLayout_4.addWidget(self.checkBoxTimeAll)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.startLabel = QtWidgets.QLabel(self.groupBoxTime)
        self.startLabel.setObjectName("startLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startLabel)
        self.startSpinBox = QtWidgets.QSpinBox(self.groupBoxTime)
        self.startSpinBox.setEnabled(True)
        self.startSpinBox.setObjectName("startSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startSpinBox)
        self.endSpinBox = QtWidgets.QSpinBox(self.groupBoxTime)
        self.endSpinBox.setObjectName("endSpinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endSpinBox)
        self.endLabel = QtWidgets.QLabel(self.groupBoxTime)
        self.endLabel.setObjectName("endLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.endLabel)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        self.comboBoxUnits = QtWidgets.QComboBox(self.groupBoxTime)
        self.comboBoxUnits.setObjectName("comboBoxUnits")
        self.comboBoxUnits.addItem("")
        self.comboBoxUnits.addItem("")
        self.comboBoxUnits.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxUnits)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBoxTime)
        self.groupBoxCondition = QtWidgets.QGroupBox(WidgetIsolate)
        self.groupBoxCondition.setObjectName("groupBoxCondition")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBoxCondition)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(self.groupBoxCondition)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.groupBoxCondition)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxPreview = QtWidgets.QCheckBox(WidgetIsolate)
        self.checkBoxPreview.setObjectName("checkBoxPreview")
        self.horizontalLayout.addWidget(self.checkBoxPreview)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(WidgetIsolate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(WidgetIsolate)
        self.tabWidgetRoiTypes.setCurrentIndex(0)
        self.comboBoxUnits.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(WidgetIsolate)

    def retranslateUi(self, WidgetIsolate):
        _translate = QtCore.QCoreApplication.translate
        WidgetIsolate.setWindowTitle(_translate("WidgetIsolate", "Isolate"))
        self.labelSource.setText(_translate("WidgetIsolate", "Source:"))
        self.labelROIs.setText(_translate("WidgetIsolate", "ROIs:"))
        self.comboBoxROIs.setItemText(0, _translate("WidgetIsolate", "*New*"))
        self.originXLabel.setText(_translate("WidgetIsolate", "Origin, X (px)"))
        self.originXLineEdit.setText(_translate("WidgetIsolate", "0"))
        self.originYLabel.setText(_translate("WidgetIsolate", "Origin, Y (px)"))
        self.originYLineEdit.setText(_translate("WidgetIsolate", "0"))
        self.radiusLabel.setText(_translate("WidgetIsolate", "Radius (px)"))
        self.tabWidgetRoiTypes.setTabText(self.tabWidgetRoiTypes.indexOf(self.tabCircle), _translate("WidgetIsolate", "Circle Region"))
        self.tabWidgetRoiTypes.setTabText(self.tabWidgetRoiTypes.indexOf(self.tabPoly), _translate("WidgetIsolate", "Poly Region"))
        self.groupBoxTime.setTitle(_translate("WidgetIsolate", "Time Span"))
        self.checkBoxTimeAll.setText(_translate("WidgetIsolate", "Use All"))
        self.startLabel.setText(_translate("WidgetIsolate", "Start"))
        self.endLabel.setText(_translate("WidgetIsolate", "End"))
        self.comboBoxUnits.setCurrentText(_translate("WidgetIsolate", "ms"))
        self.comboBoxUnits.setItemText(0, _translate("WidgetIsolate", "frames"))
        self.comboBoxUnits.setItemText(1, _translate("WidgetIsolate", "ms"))
        self.comboBoxUnits.setItemText(2, _translate("WidgetIsolate", "s"))
        self.groupBoxCondition.setTitle(_translate("WidgetIsolate", "Condition"))
        self.checkBox.setText(_translate("WidgetIsolate", "Invert Signal"))
        self.checkBoxPreview.setText(_translate("WidgetIsolate", "Preview"))

