# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\KairoSight_WindowMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, WindowMain):
        WindowMain.setObjectName("WindowMain")
        WindowMain.resize(886, 788)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WindowMain.sizePolicy().hasHeightForWidth())
        WindowMain.setSizePolicy(sizePolicy)
        WindowMain.setMinimumSize(QtCore.QSize(886, 788))
        self.horizontalLayoutWindowMain = QtWidgets.QHBoxLayout(WindowMain)
        self.horizontalLayoutWindowMain.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayoutWindowMain.setObjectName("horizontalLayoutWindowMain")
        self.LayoutVideo = QtWidgets.QVBoxLayout()
        self.LayoutVideo.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LayoutVideo.setObjectName("LayoutVideo")
        self.horizontalLayout_View = QtWidgets.QHBoxLayout()
        self.horizontalLayout_View.setSpacing(0)
        self.horizontalLayout_View.setObjectName("horizontalLayout_View")
        self.graphicsView = GraphicsWidget(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(256, 0))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_View.addWidget(self.graphicsView)
        self.LayoutVideo.addLayout(self.horizontalLayout_View)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalScrollBar = QtWidgets.QScrollBar(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setInvertedAppearance(False)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout.addWidget(self.horizontalScrollBar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lcdNumber = QtWidgets.QLCDNumber(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.LayoutVideo.addLayout(self.horizontalLayout)
        self.widgetPreviewPlot = GraphicsLayoutWidget(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPreviewPlot.sizePolicy().hasHeightForWidth())
        self.widgetPreviewPlot.setSizePolicy(sizePolicy)
        self.widgetPreviewPlot.setMinimumSize(QtCore.QSize(70, 100))
        self.widgetPreviewPlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetPreviewPlot.setObjectName("widgetPreviewPlot")
        self.LayoutVideo.addWidget(self.widgetPreviewPlot)
        self.widgetPreviewPlot_2 = GraphicsLayoutWidget(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPreviewPlot_2.sizePolicy().hasHeightForWidth())
        self.widgetPreviewPlot_2.setSizePolicy(sizePolicy)
        self.widgetPreviewPlot_2.setMinimumSize(QtCore.QSize(70, 100))
        self.widgetPreviewPlot_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetPreviewPlot_2.setObjectName("widgetPreviewPlot_2")
        self.LayoutVideo.addWidget(self.widgetPreviewPlot_2)
        self.horizontalLayoutWindowMain.addLayout(self.LayoutVideo)
        self.LayoutSteps = QtWidgets.QVBoxLayout()
        self.LayoutSteps.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.LayoutSteps.setObjectName("LayoutSteps")
        self.groupBoxPrep = QtWidgets.QGroupBox(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPrep.sizePolicy().hasHeightForWidth())
        self.groupBoxPrep.setSizePolicy(sizePolicy)
        self.groupBoxPrep.setMinimumSize(QtCore.QSize(600, 200))
        self.groupBoxPrep.setMaximumSize(QtCore.QSize(400, 200))
        self.groupBoxPrep.setObjectName("groupBoxPrep")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxPrep)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolBoxPrep_Props = QtWidgets.QToolBox(self.groupBoxPrep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxPrep_Props.sizePolicy().hasHeightForWidth())
        self.toolBoxPrep_Props.setSizePolicy(sizePolicy)
        self.toolBoxPrep_Props.setObjectName("toolBoxPrep_Props")
        self.pageProps = QtWidgets.QWidget()
        self.pageProps.setGeometry(QtCore.QRect(0, 0, 115, 113))
        self.pageProps.setObjectName("pageProps")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageProps)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonNext = QtWidgets.QCommandLinkButton(self.pageProps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext.sizePolicy().hasHeightForWidth())
        self.buttonNext.setSizePolicy(sizePolicy)
        self.buttonNext.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout_2.addWidget(self.buttonNext)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.toolBoxPrep_Props.addItem(self.pageProps, "")
        self.pagePropsEdit = QtWidgets.QWidget()
        self.pagePropsEdit.setGeometry(QtCore.QRect(0, 0, 69, 113))
        self.pagePropsEdit.setObjectName("pagePropsEdit")
        self.toolBoxPrep_Props.addItem(self.pagePropsEdit, "")
        self.horizontalLayout_3.addWidget(self.toolBoxPrep_Props)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.toolBoxPrep_Crop = QtWidgets.QToolBox(self.groupBoxPrep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxPrep_Crop.sizePolicy().hasHeightForWidth())
        self.toolBoxPrep_Crop.setSizePolicy(sizePolicy)
        self.toolBoxPrep_Crop.setObjectName("toolBoxPrep_Crop")
        self.pageCrop = QtWidgets.QWidget()
        self.pageCrop.setGeometry(QtCore.QRect(0, 0, 162, 113))
        self.pageCrop.setObjectName("pageCrop")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageCrop)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_2 = QtWidgets.QCheckBox(self.pageCrop)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.buttonNext_2 = QtWidgets.QCommandLinkButton(self.pageCrop)
        self.buttonNext_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext_2.sizePolicy().hasHeightForWidth())
        self.buttonNext_2.setSizePolicy(sizePolicy)
        self.buttonNext_2.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext_2.setObjectName("buttonNext_2")
        self.horizontalLayout_6.addWidget(self.buttonNext_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.toolBoxPrep_Crop.addItem(self.pageCrop, "")
        self.pageCropEdit = QtWidgets.QWidget()
        self.pageCropEdit.setGeometry(QtCore.QRect(0, 0, 100, 113))
        self.pageCropEdit.setObjectName("pageCropEdit")
        self.toolBoxPrep_Crop.addItem(self.pageCropEdit, "")
        self.horizontalLayout_3.addWidget(self.toolBoxPrep_Crop)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.toolBoxPrep_Mask = QtWidgets.QToolBox(self.groupBoxPrep)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxPrep_Mask.sizePolicy().hasHeightForWidth())
        self.toolBoxPrep_Mask.setSizePolicy(sizePolicy)
        self.toolBoxPrep_Mask.setObjectName("toolBoxPrep_Mask")
        self.pageMask = QtWidgets.QWidget()
        self.pageMask.setGeometry(QtCore.QRect(0, 0, 163, 113))
        self.pageMask.setObjectName("pageMask")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageMask)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.pageMask)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_7.addWidget(self.checkBox_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.buttonNext_3 = QtWidgets.QCommandLinkButton(self.pageMask)
        self.buttonNext_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext_3.sizePolicy().hasHeightForWidth())
        self.buttonNext_3.setSizePolicy(sizePolicy)
        self.buttonNext_3.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext_3.setObjectName("buttonNext_3")
        self.horizontalLayout_7.addWidget(self.buttonNext_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.toolBoxPrep_Mask.addItem(self.pageMask, "")
        self.pageMaskEdit = QtWidgets.QWidget()
        self.pageMaskEdit.setGeometry(QtCore.QRect(0, 0, 100, 113))
        self.pageMaskEdit.setObjectName("pageMaskEdit")
        self.toolBoxPrep_Mask.addItem(self.pageMaskEdit, "")
        self.horizontalLayout_3.addWidget(self.toolBoxPrep_Mask)
        self.Prep_Preview = GraphicsLayoutWidget(self.groupBoxPrep)
        self.Prep_Preview.setMinimumSize(QtCore.QSize(70, 70))
        self.Prep_Preview.setMaximumSize(QtCore.QSize(70, 70))
        self.Prep_Preview.setObjectName("Prep_Preview")
        self.horizontalLayout_3.addWidget(self.Prep_Preview)
        self.LayoutSteps.addWidget(self.groupBoxPrep)
        self.progressBar_Preparation = QtWidgets.QProgressBar(WindowMain)
        self.progressBar_Preparation.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_Preparation.setMinimum(0)
        self.progressBar_Preparation.setMaximum(4)
        self.progressBar_Preparation.setProperty("value", 1)
        self.progressBar_Preparation.setTextVisible(False)
        self.progressBar_Preparation.setInvertedAppearance(False)
        self.progressBar_Preparation.setObjectName("progressBar_Preparation")
        self.LayoutSteps.addWidget(self.progressBar_Preparation)
        self.line_2 = QtWidgets.QFrame(WindowMain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LayoutSteps.addWidget(self.line_2)
        self.groupBoxProc = QtWidgets.QGroupBox(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxProc.sizePolicy().hasHeightForWidth())
        self.groupBoxProc.setSizePolicy(sizePolicy)
        self.groupBoxProc.setMinimumSize(QtCore.QSize(600, 200))
        self.groupBoxProc.setMaximumSize(QtCore.QSize(400, 200))
        self.groupBoxProc.setObjectName("groupBoxProc")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBoxProc)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.toolBoxProc_Normalize = QtWidgets.QToolBox(self.groupBoxProc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxProc_Normalize.sizePolicy().hasHeightForWidth())
        self.toolBoxProc_Normalize.setSizePolicy(sizePolicy)
        self.toolBoxProc_Normalize.setObjectName("toolBoxProc_Normalize")
        self.pageNormalize = QtWidgets.QWidget()
        self.pageNormalize.setGeometry(QtCore.QRect(0, 0, 115, 113))
        self.pageNormalize.setObjectName("pageNormalize")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pageNormalize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.buttonNext_9 = QtWidgets.QCommandLinkButton(self.pageNormalize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext_9.sizePolicy().hasHeightForWidth())
        self.buttonNext_9.setSizePolicy(sizePolicy)
        self.buttonNext_9.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext_9.setObjectName("buttonNext_9")
        self.horizontalLayout_13.addWidget(self.buttonNext_9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.toolBoxProc_Normalize.addItem(self.pageNormalize, "")
        self.pageNormalizeEdit = QtWidgets.QWidget()
        self.pageNormalizeEdit.setGeometry(QtCore.QRect(0, 0, 69, 113))
        self.pageNormalizeEdit.setObjectName("pageNormalizeEdit")
        self.toolBoxProc_Normalize.addItem(self.pageNormalizeEdit, "")
        self.horizontalLayout_14.addWidget(self.toolBoxProc_Normalize)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.toolBoxProc_Filter = QtWidgets.QToolBox(self.groupBoxProc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxProc_Filter.sizePolicy().hasHeightForWidth())
        self.toolBoxProc_Filter.setSizePolicy(sizePolicy)
        self.toolBoxProc_Filter.setObjectName("toolBoxProc_Filter")
        self.pageFilter = QtWidgets.QWidget()
        self.pageFilter.setGeometry(QtCore.QRect(0, 0, 162, 113))
        self.pageFilter.setObjectName("pageFilter")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageFilter)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_7 = QtWidgets.QCheckBox(self.pageFilter)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_12.addWidget(self.checkBox_7)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.buttonNext_8 = QtWidgets.QCommandLinkButton(self.pageFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext_8.sizePolicy().hasHeightForWidth())
        self.buttonNext_8.setSizePolicy(sizePolicy)
        self.buttonNext_8.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext_8.setObjectName("buttonNext_8")
        self.horizontalLayout_12.addWidget(self.buttonNext_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.toolBoxProc_Filter.addItem(self.pageFilter, "")
        self.pageFilterEdit = QtWidgets.QWidget()
        self.pageFilterEdit.setGeometry(QtCore.QRect(0, 0, 100, 113))
        self.pageFilterEdit.setObjectName("pageFilterEdit")
        self.toolBoxProc_Filter.addItem(self.pageFilterEdit, "")
        self.horizontalLayout_14.addWidget(self.toolBoxProc_Filter)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem14)
        self.toolBoxProc_SNR = QtWidgets.QToolBox(self.groupBoxProc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxProc_SNR.sizePolicy().hasHeightForWidth())
        self.toolBoxProc_SNR.setSizePolicy(sizePolicy)
        self.toolBoxProc_SNR.setObjectName("toolBoxProc_SNR")
        self.pageSNR = QtWidgets.QWidget()
        self.pageSNR.setGeometry(QtCore.QRect(0, 0, 163, 113))
        self.pageSNR.setObjectName("pageSNR")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageSNR)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_6 = QtWidgets.QCheckBox(self.pageSNR)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_11.addWidget(self.checkBox_6)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.buttonNext_7 = QtWidgets.QCommandLinkButton(self.pageSNR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext_7.sizePolicy().hasHeightForWidth())
        self.buttonNext_7.setSizePolicy(sizePolicy)
        self.buttonNext_7.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext_7.setObjectName("buttonNext_7")
        self.horizontalLayout_11.addWidget(self.buttonNext_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.toolBoxProc_SNR.addItem(self.pageSNR, "")
        self.pageSNREdit = QtWidgets.QWidget()
        self.pageSNREdit.setGeometry(QtCore.QRect(0, 0, 126, 113))
        self.pageSNREdit.setObjectName("pageSNREdit")
        self.toolBoxProc_SNR.addItem(self.pageSNREdit, "")
        self.horizontalLayout_14.addWidget(self.toolBoxProc_SNR)
        self.Proc_Preview = GraphicsLayoutWidget(self.groupBoxProc)
        self.Proc_Preview.setEnabled(True)
        self.Proc_Preview.setMinimumSize(QtCore.QSize(70, 70))
        self.Proc_Preview.setMaximumSize(QtCore.QSize(70, 70))
        self.Proc_Preview.setObjectName("Proc_Preview")
        self.horizontalLayout_14.addWidget(self.Proc_Preview)
        self.LayoutSteps.addWidget(self.groupBoxProc)
        self.progressBar_Processing = QtWidgets.QProgressBar(WindowMain)
        self.progressBar_Processing.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_Processing.setProperty("value", 0)
        self.progressBar_Processing.setTextVisible(False)
        self.progressBar_Processing.setObjectName("progressBar_Processing")
        self.LayoutSteps.addWidget(self.progressBar_Processing)
        self.line = QtWidgets.QFrame(WindowMain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.LayoutSteps.addWidget(self.line)
        self.groupBoxAnalysis = QtWidgets.QGroupBox(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxAnalysis.sizePolicy().hasHeightForWidth())
        self.groupBoxAnalysis.setSizePolicy(sizePolicy)
        self.groupBoxAnalysis.setMinimumSize(QtCore.QSize(600, 200))
        self.groupBoxAnalysis.setMaximumSize(QtCore.QSize(400, 200))
        self.groupBoxAnalysis.setCheckable(False)
        self.groupBoxAnalysis.setObjectName("groupBoxAnalysis")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBoxAnalysis)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toolBoxAnalysis_Isolate = QtWidgets.QToolBox(self.groupBoxAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxAnalysis_Isolate.sizePolicy().hasHeightForWidth())
        self.toolBoxAnalysis_Isolate.setSizePolicy(sizePolicy)
        self.toolBoxAnalysis_Isolate.setObjectName("toolBoxAnalysis_Isolate")
        self.pageIsolate = QtWidgets.QWidget()
        self.pageIsolate.setGeometry(QtCore.QRect(0, 0, 236, 113))
        self.pageIsolate.setObjectName("pageIsolate")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pageIsolate)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem17 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem17)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_8 = QtWidgets.QCheckBox(self.pageIsolate)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_15.addWidget(self.checkBox_8)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem18)
        self.buttonNext_10 = QtWidgets.QCommandLinkButton(self.pageIsolate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext_10.sizePolicy().hasHeightForWidth())
        self.buttonNext_10.setSizePolicy(sizePolicy)
        self.buttonNext_10.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext_10.setObjectName("buttonNext_10")
        self.horizontalLayout_15.addWidget(self.buttonNext_10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.toolBoxAnalysis_Isolate.addItem(self.pageIsolate, "")
        self.pageIsolateEdit = QtWidgets.QWidget()
        self.pageIsolateEdit.setGeometry(QtCore.QRect(0, 0, 236, 113))
        self.pageIsolateEdit.setObjectName("pageIsolateEdit")
        self.toolBoxAnalysis_Isolate.addItem(self.pageIsolateEdit, "")
        self.horizontalLayout_5.addWidget(self.toolBoxAnalysis_Isolate)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem19)
        self.toolBoxAnalysis_Analyze = QtWidgets.QToolBox(self.groupBoxAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxAnalysis_Analyze.sizePolicy().hasHeightForWidth())
        self.toolBoxAnalysis_Analyze.setSizePolicy(sizePolicy)
        self.toolBoxAnalysis_Analyze.setObjectName("toolBoxAnalysis_Analyze")
        self.pageAnalyze = QtWidgets.QWidget()
        self.pageAnalyze.setGeometry(QtCore.QRect(0, 0, 236, 113))
        self.pageAnalyze.setObjectName("pageAnalyze")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageAnalyze)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem20)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.buttonNext_11 = QtWidgets.QCommandLinkButton(self.pageAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNext_11.sizePolicy().hasHeightForWidth())
        self.buttonNext_11.setSizePolicy(sizePolicy)
        self.buttonNext_11.setMinimumSize(QtCore.QSize(80, 0))
        self.buttonNext_11.setMaximumSize(QtCore.QSize(80, 16777215))
        self.buttonNext_11.setObjectName("buttonNext_11")
        self.horizontalLayout_16.addWidget(self.buttonNext_11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.toolBoxAnalysis_Analyze.addItem(self.pageAnalyze, "")
        self.pageAnalyzeEdit = QtWidgets.QWidget()
        self.pageAnalyzeEdit.setGeometry(QtCore.QRect(0, 0, 236, 113))
        self.pageAnalyzeEdit.setObjectName("pageAnalyzeEdit")
        self.toolBoxAnalysis_Analyze.addItem(self.pageAnalyzeEdit, "")
        self.horizontalLayout_5.addWidget(self.toolBoxAnalysis_Analyze)
        self.Analysis_Preview = GraphicsLayoutWidget(self.groupBoxAnalysis)
        self.Analysis_Preview.setMinimumSize(QtCore.QSize(70, 70))
        self.Analysis_Preview.setMaximumSize(QtCore.QSize(70, 70))
        self.Analysis_Preview.setObjectName("Analysis_Preview")
        self.horizontalLayout_5.addWidget(self.Analysis_Preview)
        self.LayoutSteps.addWidget(self.groupBoxAnalysis)
        self.progressBar_Analysis = QtWidgets.QProgressBar(WindowMain)
        self.progressBar_Analysis.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_Analysis.setProperty("value", 0)
        self.progressBar_Analysis.setTextVisible(False)
        self.progressBar_Analysis.setObjectName("progressBar_Analysis")
        self.LayoutSteps.addWidget(self.progressBar_Analysis)
        self.line_3 = QtWidgets.QFrame(WindowMain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.LayoutSteps.addWidget(self.line_3)
        self.textBrowser_Feedback = QtWidgets.QTextBrowser(WindowMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Feedback.sizePolicy().hasHeightForWidth())
        self.textBrowser_Feedback.setSizePolicy(sizePolicy)
        self.textBrowser_Feedback.setMinimumSize(QtCore.QSize(0, 75))
        self.textBrowser_Feedback.setMaximumSize(QtCore.QSize(16777215, 75))
        self.textBrowser_Feedback.setObjectName("textBrowser_Feedback")
        self.LayoutSteps.addWidget(self.textBrowser_Feedback)
        self.horizontalLayoutWindowMain.addLayout(self.LayoutSteps)

        self.retranslateUi(WindowMain)
        self.toolBoxPrep_Props.setCurrentIndex(0)
        self.toolBoxPrep_Crop.setCurrentIndex(0)
        self.toolBoxPrep_Mask.setCurrentIndex(0)
        self.toolBoxProc_Normalize.setCurrentIndex(0)
        self.toolBoxProc_Filter.setCurrentIndex(0)
        self.toolBoxProc_SNR.setCurrentIndex(0)
        self.toolBoxAnalysis_Isolate.setCurrentIndex(0)
        self.toolBoxAnalysis_Analyze.setCurrentIndex(0)
        self.horizontalScrollBar.valueChanged['int'].connect(self.lcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(WindowMain)

    def retranslateUi(self, WindowMain):
        _translate = QtCore.QCoreApplication.translate
        WindowMain.setWindowTitle(_translate("WindowMain", "KairoSight - Main Window"))
        self.groupBoxPrep.setTitle(_translate("WindowMain", "Preparation"))
        self.buttonNext.setText(_translate("WindowMain", "Next"))
        self.toolBoxPrep_Props.setItemText(self.toolBoxPrep_Props.indexOf(self.pageProps), _translate("WindowMain", "Properties"))
        self.toolBoxPrep_Props.setItemText(self.toolBoxPrep_Props.indexOf(self.pagePropsEdit), _translate("WindowMain", "<Edit>"))
        self.checkBox_2.setText(_translate("WindowMain", "Skip"))
        self.buttonNext_2.setText(_translate("WindowMain", "Next"))
        self.toolBoxPrep_Crop.setItemText(self.toolBoxPrep_Crop.indexOf(self.pageCrop), _translate("WindowMain", "Crop"))
        self.toolBoxPrep_Crop.setItemText(self.toolBoxPrep_Crop.indexOf(self.pageCropEdit), _translate("WindowMain", "<Edit>"))
        self.checkBox_3.setText(_translate("WindowMain", "Skip"))
        self.buttonNext_3.setText(_translate("WindowMain", "Next"))
        self.toolBoxPrep_Mask.setItemText(self.toolBoxPrep_Mask.indexOf(self.pageMask), _translate("WindowMain", "Mask"))
        self.toolBoxPrep_Mask.setItemText(self.toolBoxPrep_Mask.indexOf(self.pageMaskEdit), _translate("WindowMain", "<Edit>"))
        self.groupBoxProc.setTitle(_translate("WindowMain", "Processing"))
        self.buttonNext_9.setText(_translate("WindowMain", "Next"))
        self.toolBoxProc_Normalize.setItemText(self.toolBoxProc_Normalize.indexOf(self.pageNormalize), _translate("WindowMain", "Normalize"))
        self.toolBoxProc_Normalize.setItemText(self.toolBoxProc_Normalize.indexOf(self.pageNormalizeEdit), _translate("WindowMain", "<Edit>"))
        self.checkBox_7.setText(_translate("WindowMain", "Skip"))
        self.buttonNext_8.setText(_translate("WindowMain", "Next"))
        self.toolBoxProc_Filter.setItemText(self.toolBoxProc_Filter.indexOf(self.pageFilter), _translate("WindowMain", "Filter"))
        self.toolBoxProc_Filter.setItemText(self.toolBoxProc_Filter.indexOf(self.pageFilterEdit), _translate("WindowMain", "<Edit>"))
        self.checkBox_6.setText(_translate("WindowMain", "Skip"))
        self.buttonNext_7.setText(_translate("WindowMain", "Next"))
        self.toolBoxProc_SNR.setItemText(self.toolBoxProc_SNR.indexOf(self.pageSNR), _translate("WindowMain", "Signal-to-Noise Ratio (SNR)"))
        self.toolBoxProc_SNR.setItemText(self.toolBoxProc_SNR.indexOf(self.pageSNREdit), _translate("WindowMain", "<Edit>"))
        self.groupBoxAnalysis.setTitle(_translate("WindowMain", "Analysis"))
        self.checkBox_8.setText(_translate("WindowMain", "Skip"))
        self.buttonNext_10.setText(_translate("WindowMain", "Next"))
        self.toolBoxAnalysis_Isolate.setItemText(self.toolBoxAnalysis_Isolate.indexOf(self.pageIsolate), _translate("WindowMain", "Isolate"))
        self.toolBoxAnalysis_Isolate.setItemText(self.toolBoxAnalysis_Isolate.indexOf(self.pageIsolateEdit), _translate("WindowMain", "<Edit>"))
        self.buttonNext_11.setText(_translate("WindowMain", "Next"))
        self.toolBoxAnalysis_Analyze.setItemText(self.toolBoxAnalysis_Analyze.indexOf(self.pageAnalyze), _translate("WindowMain", "Analyze"))
        self.toolBoxAnalysis_Analyze.setItemText(self.toolBoxAnalysis_Analyze.indexOf(self.pageAnalyzeEdit), _translate("WindowMain", "<Edit>"))
from pyqtgraph.widgets.GraphicsLayoutWidget import GraphicsLayoutWidget
from ui.graphicswidget import GraphicsWidget
