# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KairoSightWidgetExport.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetExport(object):
    def setupUi(self, WidgetExport):
        WidgetExport.setObjectName("WidgetExport")
        WidgetExport.resize(600, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetExport.sizePolicy().hasHeightForWidth())
        WidgetExport.setSizePolicy(sizePolicy)
        WidgetExport.setMinimumSize(QtCore.QSize(600, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WidgetExport)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.labelSource = QtWidgets.QLabel(WidgetExport)
        self.labelSource.setObjectName("labelSource")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSource)
        self.comboBoxSource = QtWidgets.QComboBox(WidgetExport)
        self.comboBoxSource.setObjectName("comboBoxSource")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxSource)
        self.labelAnalysis = QtWidgets.QLabel(WidgetExport)
        self.labelAnalysis.setObjectName("labelAnalysis")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelAnalysis)
        self.comboBoxAnalysis = QtWidgets.QComboBox(WidgetExport)
        self.comboBoxAnalysis.setObjectName("comboBoxAnalysis")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxAnalysis)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(WidgetExport)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBoxAPDs = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxAPDs.setObjectName("checkBoxAPDs")
        self.verticalLayout_4.addWidget(self.checkBoxAPDs)
        self.checkBoxOther = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxOther.setObjectName("checkBoxOther")
        self.verticalLayout_4.addWidget(self.checkBoxOther)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(WidgetExport)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxParameters = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxParameters.setObjectName("checkBoxParameters")
        self.verticalLayout_3.addWidget(self.checkBoxParameters)
        self.checkBoxProperties = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxProperties.setObjectName("checkBoxProperties")
        self.verticalLayout_3.addWidget(self.checkBoxProperties)
        self.gridLayout_2.addWidget(self.groupBox, 0, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonIndividual = QtWidgets.QRadioButton(WidgetExport)
        self.radioButtonIndividual.setChecked(True)
        self.radioButtonIndividual.setObjectName("radioButtonIndividual")
        self.verticalLayout.addWidget(self.radioButtonIndividual)
        self.radioButtonMean = QtWidgets.QRadioButton(WidgetExport)
        self.radioButtonMean.setObjectName("radioButtonMean")
        self.verticalLayout.addWidget(self.radioButtonMean)
        self.checkBoxSD = QtWidgets.QCheckBox(WidgetExport)
        self.checkBoxSD.setEnabled(False)
        self.checkBoxSD.setObjectName("checkBoxSD")
        self.verticalLayout.addWidget(self.checkBoxSD)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButtonCopy = QtWidgets.QPushButton(WidgetExport)
        self.pushButtonCopy.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonCopy.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCopy.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonCopy.setObjectName("pushButtonCopy")
        self.horizontalLayout.addWidget(self.pushButtonCopy)
        spacerItem5 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButtonExport = QtWidgets.QPushButton(WidgetExport)
        self.pushButtonExport.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonExport.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonExport.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.horizontalLayout.addWidget(self.pushButtonExport)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidgetResults = QtWidgets.QTableWidget(WidgetExport)
        self.tableWidgetResults.setObjectName("tableWidgetResults")
        self.tableWidgetResults.setColumnCount(0)
        self.tableWidgetResults.setRowCount(0)
        self.tableWidgetResults.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetResults.horizontalHeader().setMinimumSectionSize(20)
        self.verticalLayout_2.addWidget(self.tableWidgetResults)

        self.retranslateUi(WidgetExport)
        QtCore.QMetaObject.connectSlotsByName(WidgetExport)

    def retranslateUi(self, WidgetExport):
        _translate = QtCore.QCoreApplication.translate
        WidgetExport.setWindowTitle(_translate("WidgetExport", "Export"))
        self.labelSource.setText(_translate("WidgetExport", "Source:"))
        self.labelAnalysis.setText(_translate("WidgetExport", "Analysis"))
        self.groupBox_2.setTitle(_translate("WidgetExport", "Data"))
        self.checkBoxAPDs.setText(_translate("WidgetExport", "APDs"))
        self.checkBoxOther.setText(_translate("WidgetExport", "Other"))
        self.groupBox.setTitle(_translate("WidgetExport", "Metadata"))
        self.checkBoxParameters.setText(_translate("WidgetExport", "Parameters"))
        self.checkBoxProperties.setText(_translate("WidgetExport", "Properties"))
        self.radioButtonIndividual.setText(_translate("WidgetExport", "Individual"))
        self.radioButtonMean.setText(_translate("WidgetExport", "Mean"))
        self.checkBoxSD.setText(_translate("WidgetExport", "SD"))
        self.pushButtonCopy.setText(_translate("WidgetExport", "Copy"))
        self.pushButtonCopy.setShortcut(_translate("WidgetExport", "Ctrl+C"))
        self.pushButtonExport.setText(_translate("WidgetExport", "Export"))

