# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KairoSightWidgetTIFF.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetTiff(object):
    def setupUi(self, WidgetTiff):
        WidgetTiff.setObjectName("WidgetTiff")
        WidgetTiff.resize(739, 415)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(WidgetTiff)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mpl = MplWidget(WidgetTiff)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName("mpl")
        self.verticalLayout_2.addWidget(self.mpl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalScrollBar = QtWidgets.QScrollBar(WidgetTiff)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setInvertedAppearance(False)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout.addWidget(self.horizontalScrollBar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lcdNumber = QtWidgets.QLCDNumber(WidgetTiff)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxProperties = QtWidgets.QGroupBox(WidgetTiff)
        self.groupBoxProperties.setObjectName("groupBoxProperties")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxProperties)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayoutProperties = QtWidgets.QFormLayout()
        self.formLayoutProperties.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutProperties.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayoutProperties.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayoutProperties.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayoutProperties.setObjectName("formLayoutProperties")
        self.SizeLabel = QtWidgets.QLabel(self.groupBoxProperties)
        self.SizeLabel.setObjectName("SizeLabel")
        self.formLayoutProperties.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.SizeLabel)
        self.SizeLabelEdit = QtWidgets.QLabel(self.groupBoxProperties)
        self.SizeLabelEdit.setObjectName("SizeLabelEdit")
        self.formLayoutProperties.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SizeLabelEdit)
        self.frameRateLineEdit = QtWidgets.QLineEdit(self.groupBoxProperties)
        self.frameRateLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRateLineEdit.sizePolicy().hasHeightForWidth())
        self.frameRateLineEdit.setSizePolicy(sizePolicy)
        self.frameRateLineEdit.setMinimumSize(QtCore.QSize(90, 20))
        self.frameRateLineEdit.setBaseSize(QtCore.QSize(50, 20))
        self.frameRateLineEdit.setClearButtonEnabled(False)
        self.frameRateLineEdit.setObjectName("frameRateLineEdit")
        self.formLayoutProperties.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frameRateLineEdit)
        self.frameRateLabel = QtWidgets.QLabel(self.groupBoxProperties)
        self.frameRateLabel.setObjectName("frameRateLabel")
        self.formLayoutProperties.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frameRateLabel)
        self.framePeriodMsLabel = QtWidgets.QLabel(self.groupBoxProperties)
        self.framePeriodMsLabel.setObjectName("framePeriodMsLabel")
        self.formLayoutProperties.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.framePeriodMsLabel)
        self.durationMsLabel = QtWidgets.QLabel(self.groupBoxProperties)
        self.durationMsLabel.setObjectName("durationMsLabel")
        self.formLayoutProperties.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.durationMsLabel)
        self.durationMsLineEdit = QtWidgets.QLineEdit(self.groupBoxProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durationMsLineEdit.sizePolicy().hasHeightForWidth())
        self.durationMsLineEdit.setSizePolicy(sizePolicy)
        self.durationMsLineEdit.setMinimumSize(QtCore.QSize(90, 20))
        self.durationMsLineEdit.setObjectName("durationMsLineEdit")
        self.formLayoutProperties.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.durationMsLineEdit)
        self.resolutionLineEdit = QtWidgets.QLineEdit(self.groupBoxProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolutionLineEdit.sizePolicy().hasHeightForWidth())
        self.resolutionLineEdit.setSizePolicy(sizePolicy)
        self.resolutionLineEdit.setMinimumSize(QtCore.QSize(90, 20))
        self.resolutionLineEdit.setObjectName("resolutionLineEdit")
        self.formLayoutProperties.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.resolutionLineEdit)
        self.framePeriodMsLineEdit = QtWidgets.QLineEdit(self.groupBoxProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePeriodMsLineEdit.sizePolicy().hasHeightForWidth())
        self.framePeriodMsLineEdit.setSizePolicy(sizePolicy)
        self.framePeriodMsLineEdit.setMinimumSize(QtCore.QSize(90, 20))
        self.framePeriodMsLineEdit.setClearButtonEnabled(False)
        self.framePeriodMsLineEdit.setObjectName("framePeriodMsLineEdit")
        self.formLayoutProperties.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.framePeriodMsLineEdit)
        self.resolutionLabel = QtWidgets.QLabel(self.groupBoxProperties)
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.formLayoutProperties.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.resolutionLabel)
        self.horizontalLayout_4.addLayout(self.formLayoutProperties)
        self.verticalLayout.addWidget(self.groupBoxProperties)
        self.groupBox = QtWidgets.QGroupBox(WidgetTiff)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.columnView = QtWidgets.QColumnView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.columnView.sizePolicy().hasHeightForWidth())
        self.columnView.setSizePolicy(sizePolicy)
        self.columnView.setResizeGripsVisible(False)
        self.columnView.setObjectName("columnView")
        self.verticalLayout_3.addWidget(self.columnView)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(WidgetTiff)
        self.horizontalScrollBar.valueChanged['int'].connect(self.lcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(WidgetTiff)

    def retranslateUi(self, WidgetTiff):
        _translate = QtCore.QCoreApplication.translate
        WidgetTiff.setWindowTitle(_translate("WidgetTiff", "TIFF Viewer"))
        self.groupBoxProperties.setTitle(_translate("WidgetTiff", "Properties"))
        self.SizeLabel.setText(_translate("WidgetTiff", "Width x Height"))
        self.SizeLabelEdit.setText(_translate("WidgetTiff", "---- X ----"))
        self.frameRateLineEdit.setPlaceholderText(_translate("WidgetTiff", "Nan"))
        self.frameRateLabel.setText(_translate("WidgetTiff", "Frame Rate (fps)"))
        self.framePeriodMsLabel.setText(_translate("WidgetTiff", "Frame Period (ms)"))
        self.durationMsLabel.setText(_translate("WidgetTiff", "Duration (ms)"))
        self.durationMsLineEdit.setPlaceholderText(_translate("WidgetTiff", "Nan"))
        self.resolutionLineEdit.setPlaceholderText(_translate("WidgetTiff", "Nan"))
        self.framePeriodMsLineEdit.setPlaceholderText(_translate("WidgetTiff", "Nan"))
        self.resolutionLabel.setText(_translate("WidgetTiff", "Resolution (cm/px)"))
        self.groupBox.setTitle(_translate("WidgetTiff", "Data Tree"))

from mplwidget import MplWidget
